# Generated by Django 2.0.5 on 2018-05-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cli_rg',
            field=models.IntegerField(default=70),
        ),
    ]
