# Generated by Django 2.0.5 on 2018-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cliente_cli_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cli_rg',
            field=models.IntegerField(default=0),
        ),
    ]
