# Generated by Django 2.0.5 on 2018-05-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180531_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cli_rg',
        ),
    ]
