# Generated by Django 2.0.5 on 2018-05-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180531_1438'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cli_nome',
            new_name='cli_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='cli_rg',
            new_name='cli_register',
        ),
    ]
