# Generated by Django 2.0.5 on 2018-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180531_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nt_name', models.CharField(max_length=50)),
                ('nt_register', models.IntegerField()),
            ],
        ),
    ]
